---
- name: install basic tools
  yum: pkg={{item}}  state=installed update_cache=true
  with_items:
    - vim
    - unzip
    - bzip2
    - nc
    - wget
    - git
    - bash-completion

- include: letsencrypt.yml
